PIVOT_CURRENT_LIMIT = 20
ROLLER_CURRENT_LIMIT = 20

STRESSED_INTAKE_CURRENT_DRAW = 0
INTAKE_PIVOT_SPEED = 0.15
ROLLER_SPEED = 0.5

RIGHT_PIVOT_INVERTED = False
LEFT_PIVOT_INVERTED = False

RIGHT_PIVOT_ID = 0
LEFT_PIVOT_ID = 1
ROLLER_ID = 2
